## API gateway to get rid of CORS nonsense in between frontend and backend services

apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: proxy:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: proxy
  namespace: default
spec:
  selector:
    app: proxy
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
